import "src/app/globals.css";
import { Ubuntu } from "next/font/google";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: "400", // Add a valid weight value
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={ubuntu.className}>
      <body className="bg-stone-950">{children}</body>
    </html>
  );
}
